import type { Project } from '../types';
import { baselineDoc, DISCIPLINE_LABEL, docIssues, docsOf, isSuperseded } from '../model/receivedDocs';
import { describeOp, STATUS_LABEL as MOD_STATUS } from '../model/designChanges';
import { CATEGORY_LABEL, STATUS_LABEL, SEVERITY_LABEL } from '../model/reviewComments';
import type { Block, ReviewDoc, ReviewReportSetup } from './reviewReport';

/** A contractor's technical-clarification report: the received design it is about, the discrepancies found in it, the changes
 * proposed, and the questions put to the design's author. Built from one frozen copy of the project and rendered by the same
 * PDF and Word code as the design review report. Pricing is not here: the BOQ basis and rates are a separate document. */
const MISSING = 'Not recorded';
const v = (x?: string) => (x?.trim() ? x : MISSING);

export function buildClarificationDoc(source: Project, setup: Pick<ReviewReportSetup, 'title' | 'docNo' | 'preparedBy' | 'purpose'>, now = new Date()): ReviewDoc {
  const p: Project = JSON.parse(JSON.stringify(source));
  const info = p.info ?? {}, base = baselineDoc(p), docs = docsOf(p).filter((d) => !isSuperseded(d));
  const all = p.reviewComments ?? [], mods = p.modifications ?? [];
  const live = all.filter((c) => c.status !== 'withdrawn');
  const findings = live.filter((c) => c.kind !== 'question'), questions = live.filter((c) => c.kind === 'question');
  const title = setup.title?.trim() || 'Technical clarification report';
  const sec = (id: string, t: string, blocks: Block[]) => ({ id, title: t, blocks });
  const ref = (c: (typeof all)[number]) => (c.ref ? c.ref.id : c.sheet ?? '—');

  return {
    title, project: p.name,
    sections: [
      sec('control', 'Document control', [{ kind: 'table', headers: ['Item', 'Value'], rows: [
        ['Project', p.name], ['Report', title], ['Document no.', v(setup.docNo)], ['Purpose', v(setup.purpose)], ['Date', now.toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })],
        ['Contractor', v(info.contractor)], ['Consultant', v(info.consultant)], ['Prepared by', v(setup.preparedBy)]
      ] }]),
      sec('reference', 'Design reference', [
        base ? { kind: 'para', text: `The design this report is about: ${base.title}, ${base.number} revision ${base.revision}${base.dateReceived ? `, received ${base.dateReceived}` : ''}${base.originator ? ` from ${base.originator}` : ''}.` }
          : { kind: 'para', text: 'No received document is marked as the design this report is about. Mark one in Received documents.' },
        ...docIssues(p).map((t): Block => ({ kind: 'para', text: t, muted: true })),
        docs.length ? { kind: 'table', headers: ['Title', 'Number', 'Rev', 'Received', 'Originator', 'Discipline', 'Use'], rows: docs.map((d) => [d.title, d.number, d.revision, v(d.dateReceived), v(d.originator), DISCIPLINE_LABEL[d.discipline], d.use === 'baseline' ? 'Reference design' : 'Reference only']) } : { kind: 'para', text: 'No documents registered.' }
      ]),
      sec('discrepancies', 'Discrepancies found', [findings.length
        ? { kind: 'table', headers: ['ID', 'Category', 'Severity', 'About', 'Discrepancy', 'Reference', 'Status', 'Response'], rows: findings.map((c) => [c.id, CATEGORY_LABEL[c.category], SEVERITY_LABEL[c.severity], ref(c), c.finding, v(c.criterion), STATUS_LABEL[c.status], c.response ?? MISSING]) }
        : { kind: 'para', text: 'No discrepancies recorded.' }]),
      sec('changes', 'Proposed changes', [mods.length
        ? { kind: 'table', headers: ['Record', 'Title', 'Reason', 'Status', 'Item', 'Current', 'Proposed'], rows: mods.flatMap((m) => (m.ops.length ? m.ops : [undefined]).map((op) => { const d = op && describeOp(op); return [m.id, m.title, v(m.reason), MOD_STATUS[m.status], d?.item ?? '—', d?.from ?? '—', d?.to ?? '—']; })) }
        : { kind: 'para', text: 'No changes proposed.' }]),
      sec('questions', 'Questions', [questions.length
        ? { kind: 'table', headers: ['ID', 'About', 'Question', 'Needed from', 'Status', 'Answer'], rows: questions.map((c) => [c.id, ref(c), c.finding, v(c.assignedTo), STATUS_LABEL[c.status], c.response ?? MISSING]) }
        : { kind: 'para', text: 'No open questions.' }]),
      sec('conclusion', 'Notes', [{ kind: 'para', text: 'This report asks for clarification and records discrepancies in the received design. It is not an approval, and it does not price the work: the BOQ basis and rates are issued separately. Names are typed text; the application does not verify identity.', muted: true }])
    ],
    footer: `Generated by LV Design Studio from a frozen copy of the project on ${now.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}.`
  };
}
