import { dmSubstationAreas, dmType, DM_TITLE, DM_UNDERTAKING } from '../calc/dmSubstation';
import { revisionStamp } from '../model/revisions';
import type { DmSubstationRoom, Project } from '../types';
import { esc } from './report';

/** DM-D-013 in English: one A4 page per substation with the minimum room
 * sizes, the notes and conditions for its type, the consultant / contractor
 * remarks, the undertaking and the signature block — laid out like the
 * Dubai Municipality sheet. */

const m = (v: number) => v.toFixed(2).replace(/\.?0+$/, '');

export function buildDmFormHtml(project: Project, substations: DmSubstationRoom[]): string {
  const info = project.info ?? {};
  const pages = substations.map((s) => {
    const r = dmSubstationAreas(s.type, s.transformers);
    const rows = r.rooms.map((x) => `<tr>
      <td class="l"><b>${esc(x.label)}</b></td><td>${m(x.lengthM)}</td><td>${m(x.widthM)}</td><td>${x.heightM ? m(x.heightM) : '—'}</td><td><b>${m(x.areaM2)}</b></td><td class="l">${esc(x.widthNote)}</td></tr>`).join('');
    return `
<section class="page">
  <header>
    <div><b>Dubai Municipality</b><span>Form DM-D-013 — English version</span></div>
    <div class="r">${esc(revisionStamp(project))}</div>
  </header>
  <h1>${esc(DM_TITLE)}</h1>
  <table class="meta">
    <tr><th>Project</th><td>${esc(project.name)}</td><th>Plot no.</th><td>${esc(info.plotNo ?? '')}</td></tr>
    <tr><th>Owner</th><td>${esc(info.owner ?? '')}</td><th>Area</th><td>${esc(info.area ?? '')}</td></tr>
    <tr><th>Consultant</th><td>${esc(info.consultant ?? '')}</td><th>Contractor</th><td>${esc(info.contractor ?? '')}</td></tr>
    <tr><th>Substation</th><td><b>${esc(s.name)}</b>${s.building ? ` — ${esc(s.building)}` : ''}</td><th>Type</th><td>${esc(dmType(s.type).label)}</td></tr>
    <tr><th>Number of transformers</th><td><b>${s.transformers}</b>${s.kva ? ` × ${s.kva} kVA` : ''}</td><th></th><td></td></tr>
  </table>
  ${r.error ? `<p class="err">${esc(r.error)}</p>` : `
  <h2>Minimum required areas</h2>
  <table class="rooms">
    <thead><tr><th class="l">Room</th><th>Length (m)</th><th>Width (m)</th><th>Height (m)</th><th>Area (m²)</th><th class="l">Condition</th></tr></thead>
    <tbody>${rows}</tbody>
    ${r.rooms.length > 1 ? `<tfoot><tr><td class="l">Total</td><td></td><td></td><td></td><td><b>${m(r.totalAreaM2)}</b></td><td></td></tr></tfoot>` : ''}
  </table>`}
  <h2>Notes and conditions</h2>
  <ol>${r.notes.map((n) => `<li>${esc(n)}</li>`).join('')}</ol>
  <h2>Consultant / contractor remarks</h2>
  <div class="box">${esc(s.remarks ?? '')}</div>
  <h2>Undertaking</h2>
  <p>${esc(DM_UNDERTAKING)}</p>
  <table class="sign"><tr><th>Submitted by</th><td>${esc(info.consultant ?? '')}</td><th>Stamp / signature</th><td></td></tr></table>
  <p class="foot">Translated from the Dubai Municipality Arabic form. The Arabic original governs. Generated by LV Design Studio.</p>
</section>`;
  }).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(project.name)} — DM-D-013 substation areas</title><style>
    @page { size: A4 portrait; margin: 14mm 14mm; }
    body { font: 10.5px/1.45 Arial, sans-serif; color: #17202e; margin: 0; }
    .page { break-after: page; } .page:last-child { break-after: auto; }
    header { display: flex; justify-content: space-between; border-bottom: 2px solid #17202e; padding-bottom: 4px; }
    header div { display: grid; } header span { color: #5b6b82; font-size: 9px; } header .r { text-align: right; font-size: 9px; }
    h1 { font-size: 15px; margin: 12px 0 10px; text-align: center; }
    h2 { font-size: 11.5px; margin: 14px 0 5px; color: #1d4f8f; border-bottom: 1px solid #1d4f8f; padding-bottom: 2px; }
    table { border-collapse: collapse; width: 100%; } th, td { border: 1px solid #9aa6b8; padding: 4px 6px; text-align: center; }
    th { background: #eef2f7; font-weight: 600; } .l { text-align: left; }
    .meta th { width: 20%; text-align: left; } .meta td { text-align: left; }
    .rooms tfoot td { background: #f5f7fa; font-weight: 600; }
    ol { margin: 4px 0; padding-left: 18px; } li { margin-bottom: 3px; }
    .box { border: 1px solid #9aa6b8; min-height: 60px; padding: 6px; white-space: pre-wrap; }
    .sign th { width: 18%; } .sign td { height: 40px; text-align: left; }
    .err { color: #c21f32; font-weight: 700; font-size: 12px; }
    .foot { color: #6a7689; font-size: 8.5px; margin-top: 12px; }
  </style></head><body>${pages}</body></html>`;
}
